'use strict';

const MINIMUM_INPUT_WIDTH = 11;
const BORDER_HORIZONTAL_WIDTH = 2;

exports.BORDER_HORIZONTAL_WIDTH = BORDER_HORIZONTAL_WIDTH;
exports.MINIMUM_INPUT_WIDTH = MINIMUM_INPUT_WIDTH;
//# sourceMappingURL=form.js.map
